name: 错误反馈
description: '提交 mihomo-party 漏洞'
title: '[Bug] '
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: 在提交之前，请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
      options:
        - label: 我已在标题简短的描述了我所遇到的问题
        - label: 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
        - label: 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
        - label: 这是 GUI 程序的问题，而不是内核程序的问题
        - label: 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
        - label: 我已经使用最新的测试版本测试过，问题依旧存在

  - type: dropdown
    attributes:
      label: 操作系统
      description: 请提供操作系统类型
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    attributes:
      label: 系统版本
      description: 请提供出现问题的操作系统版本
    validations:
      required: true
  - type: input
    attributes:
      label: 发生问题 mihomo-party 版本
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述
      description: 请提供错误的详细描述。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重现方式
      description: 请提供重现错误的步骤
    validations:
      required: true
